### PR TITLE
Prefer calculation from actual time rather than increment `set*`

### LINKED ISSUE #484: Timer doesn't look working precisely if mobu goes background
## Problem

mobu's timer doesn't work precisely if the browser tab that shows mobu is not active.
For example, even if the interval is 15min, sometimes the alert will be notified about 30 or 40 minutes later.

I think typically this occurs a user who is the mobu facilitator who is also the mobu driver.

### PR DESCRIPTION
**Pull request by kachick**
Fixes #484

I have avoided worker based solutions as written as https://github.com/mobu-of-the-world/mobu/issues/484#issuecomment-1170698402.

The choice is actual duration based, I guess it `reduces` the differences even in background tabs. (Should not be perfect.)

https://stackoverflow.com/a/5927432/1212807

I hope background tasks should not take high power. So I hope this resolves the issues...

@pankona Could you review? (I didn't check long time run.)

### CODE REVIEW

File: src/session/Timer.tsx [hunk 1]
```diff
@@ -11,6 +11,10 @@ import audiofile from "./assets/bell.mp3";
 import { readableElapsedTime } from "./timeHelpers";
 import { useInterval } from "../common/timerHooks";
 
+function secondsFromMilliseconds(milliseconds: number): number {
```
Comment (pankona) [inline src/session/Timer.tsx:14]: In this case, can we use arrow function? Do you prefer function declaration style here?

Comment (kachick) [reply src/session/Timer.tsx]: Talked with @pankona, he strongly want arrow function anywhere. So I added commit as https://github.com/mobu-of-the-world/mobu/commit/3bc7db9daec7d562955c50a33fd5242192cb8212 (commit message is mistaken 😋 )
